[supervisord]
nodaemon=true

[program:daemon]
command=python3 /app/worker.py
autostart=true
autorestart=true

[program:metadata]
command=python3 /app/metadata_service.py
autostart=true
autorestart=true
